# Generated by Django 3.1.7 on 2021-04-03 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectOwner', to='Project.crowduser'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user_comment',
            field=models.ManyToManyField(null=True, related_name='user_comment_join', through='Project.ProjectComment', to='Project.CrowdUser'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user_donation',
            field=models.ManyToManyField(null=True, related_name='user_donation_join', through='Project.ProjectDonation', to='Project.CrowdUser'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user_rate',
            field=models.ManyToManyField(null=True, related_name='user_rate_join', through='Project.ProjectRate', to='Project.CrowdUser'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user_report',
            field=models.ManyToManyField(null=True, related_name='user_report_join', through='Project.ProjectReport', to='Project.CrowdUser'),
        ),
    ]
