# Generated by Django 3.1.7 on 2021-04-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20210403_2031'),
        ('Project', '0004_auto_20210403_1807'),
    ]

    operations = [
    ]
