# Generated by Django 3.1.7 on 2021-04-06 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210404_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyption mobile phone number starting with +(country code)', regex='01[0125][0-9]{8}')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picutre',
            field=models.ImageField(blank=True, default='images/avatardefault.png', null=True, upload_to='images/'),
        ),
    ]
