# Generated by Django 3.1.7 on 2021-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210406_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faceboock_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000.0, max_digits=10, null=True),
        ),
    ]
